[[ $- == *i* ]] && source /usr/share/blesh/ble.sh --noattach
PROMPT_COMMAND='PS1_CMD1=$(ip route get 1.1.1.1 | awk -F"src " '"'"'NR == 1{ split($2, a," ");print a[1]}'"'"')';
PS1='\033[31m[\033[32m\u\033[31m@\033[32m${PS1_CMD1}\033[31m] \033[25m\w\033[31m > \033[0m'

function ls(){
	lsd $@
}


[[ ${BLE_VERSION-} ]] && ble-attach
